### ISSUE TITLE
Management-center admin user already exists error

### ISSUE THREAD

**Issue by jperucha** [hazelcast/charts#158] opened 2020-09-23 14:39 UTC
Whenever I set up the helm chart property `mancenter.adminCredentialsSecretName` and the pod recreates after a failure, the following pods recreations will fail on a crash loop back due to the following error.
This error happens without mancenter persistence enabled.

```
using automatic sizing of heap size by up to 80% of available memory and starting with container support
executing command specified by MC_INIT_CMD for container initialization
2020-09-23 14:34:07 [main] INFO  c.h.webmonitor.config.BuildInfo - Hazelcast Management Center version 4.2020.08, Jet client version: 4.2, IMDG client version: 4.0.1, embedded Jetty version: 9.4.30.v20200611
2020-09-23 14:34:07 [main] INFO  c.h.webmonitor.config.BuildInfo - This version of Hazelcast Management Center is tested with the following cluster minor versions: IMDG 4.0, Jet 4.2
2020-09-23 14:34:07 [main] INFO  c.h.webmonitor.config.SqlDbConfig - Checking DB for required migrations.
2020-09-23 14:34:09 [main] INFO  c.h.webmonitor.config.SqlDbConfig - Number of applied DB migrations: 0.
WARNING: Cluster null already exists.
To see the full stack trace, re-run with the -v/--verbose option.
Creating admin user
2020-09-23 14:34:13 [main] INFO  c.h.webmonitor.config.BuildInfo - Hazelcast Management Center version 4.2020.08, Jet client version: 4.2, IMDG client version: 4.0.1, embedded Jetty version: 9.4.30.v20200611
2020-09-23 14:34:13 [main] INFO  c.h.webmonitor.config.BuildInfo - This version of Hazelcast Management Center is tested with the following cluster minor versions: IMDG 4.0, Jet 4.2
2020-09-23 14:34:13 [main] INFO  c.h.webmonitor.config.SqlDbConfig - Checking DB for required migrations.
2020-09-23 14:34:19 [main] INFO  c.h.webmonitor.config.SqlDbConfig - Number of applied DB migrations: 0.
ERROR: The user with username 'admin' already exists.
To see the full stack trace, re-run with the -v/--verbose option.
```

Would it be a way to tell mancenter to skip this error as the user is already created?

**Comment by leszko** [comment] 2020-09-24 08:33
@hasancelik could you check this?

**Comment by hasancelik** [comment] 2020-10-06 12:42
Hi @jperucha,

I have reproduced the issue at my GKE cluster easily. Currently, I am discussing the possible solutions with Management Center team. I will keep you posted.

**Comment by hasancelik** [comment] 2020-10-07 06:36
@jperucha [the fix](https://github.com/hazelcast/management-center-docker/pull/42) merged into master branch at managment-center-docker repo so `latest` tag contains it:
https://hub.docker.com/repository/docker/hazelcast/management-center

Next management center release(`4.2020.09`) will be released very soon then we will update management center version at our helm charts. Until that moment, you can use `latest` tag at https://github.com/hazelcast/charts/blob/master/stable/hazelcast/values.yaml#L211

**Closed by hasancelik** 2020-10-07 06:36 UTC
Labels: bug

**Comment by emre-aydin** [comment] 2020-10-07 06:43
@jperucha just to clear any confusion, the next release will be named `4.2020.10` since we needed to postpone the release into October.
