### ISSUE TITLE
question: Is there any way to deploy mancenter alone?

### ISSUE THREAD

**Issue by jisnardo** [hazelcast/charts#167] opened 2020-10-28 08:32 UTC
Hi, Is there any way to deploy mancenter alone?

Something like:

https://github.com/hazelcast/charts/blob/master/stable/hazelcast/values.yaml#L204

But at hazelcast part.

https://github.com/hazelcast/charts/blob/master/stable/hazelcast/values.yaml#L26

Thanks.

**Comment by hasancelik** [comment] 2020-10-28 08:58
Hi @jisnardo,

It was requested before at https://github.com/hazelcast/charts/issues/161. Adding `enabled` parameter for Hazelcast IMDG is best solution we have for now, as you already mentioned it. 

Could you create a PR for it? 

BTW, I am closing this one because it is duplicate of #161. If you want to implement this enhancement, I will assign #161 to you.

**Closed by hasancelik** 2020-10-28 08:58 UTC

**Comment by jisnardo** [comment] 2020-10-28 09:08
Thanks!

**Comment by jisnardo** [comment] 2020-10-28 13:37
Here is the pr https://github.com/hazelcast/charts/pull/168
