### ISSUE TITLE
CrashLoopBackoff when metrics is enabled

### ISSUE THREAD

**Issue by xrow** [hazelcast/charts#148] opened 2020-08-05 14:00 UTC
When the following config is in place:
```
209 metrics:
210   enabled: true
211   service:
212     type: ClusterIP
213     port: 8080
214     annotations:
215       prometheus.io/scrape: "true"
216       prometheus.io/path: "/metrics"
217       prometheus.io/port: "8080"
```
we get this error:
```
########################################
# JAVA_OPTS=-javaagent:/opt/hazelcast/lib/jmx_prometheus_javaagent.jar=8080:/opt/hazelcast/jmx_agent_config.yaml -Djava.net.preferIPv4Stack=true -Djava.util.logging.config.file=/opt/hazelcast/logging.properties -XX:MaxRAMPercentage=80.0 -XX:+UseParallelGC --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED -Dhazelcast.config=/data/hazelcast/hazelcast.yaml -DserviceName=monitor01-hazelcast-enterprise -Dnamespace=monitor01 -Dhazelcast.ssl= -Dhazelcast.hotRestart=false -Dhazelcast.shutdownhook.policy=GRACEFUL -Dhazelcast.shutdownhook.enabled=true -Dhazelcast.graceful.shutdown.max.wait=10 -Dhazelcast.cluster.version.auto.upgrade.enabled=true -Dhazelcast.jmx=true  -Dhazelcast.enterprise.license.key=09019002910902 -Dhazelcast.tls.enabled=false
# CLASSPATH=/opt/hazelcast/*:/opt/hazelcast/lib/*:/opt/hazelcast/src/*
# starting now....
########################################
+ exec java -server -javaagent:/opt/hazelcast/lib/jmx_prometheus_javaagent.jar=8080:/opt/hazelcast/jmx_agent_config.yaml -Djava.net.preferIPv4Stack=true -Djava.util.logging.config.file=/opt/hazelcast/logging.properties -XX:MaxRAMPercentage=80.0 -XX:+UseParallelGC --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED -Dhazelcast.config=/data/hazelcast/hazelcast.yaml -DserviceName=monitor01-hazelcast-enterprise -Dnamespace=monitor01 -Dhazelcast.ssl= -Dhazelcast.hotRestart=false -Dhazelcast.shutdownhook.policy=GRACEFUL -Dhazelcast.shutdownhook.enabled=true -Dhazelcast.graceful.shutdown.max.wait=10 -Dhazelcast.cluster.version.auto.upgrade.enabled=true -Dhazelcast.jmx=true -Dhazelcast.enterprise.license.key=09019002910902 -Dhazelcast.tls.enabled=false com.hazelcast.core.server.HazelcastMemberStarter
Error occurred during initialization of VM
agent library failed to init: instrument
Error opening zip file or JAR manifest missing : /opt/hazelcast/lib/jmx_prometheus_javaagent.jar
```

**Comment by hasancelik** [comment] 2020-08-06 07:34
Hi @xrow,

I could not reproduce it with latest chart:

```
$ kgpo
NAME                       READY   STATUS    RESTARTS   AGE
hz-hazelcast-0             1/1     Running   0          119s
hz-hazelcast-1             1/1     Running   0          77s
hz-hazelcast-2             0/1     Running   0          42s
hz-hazelcast-mancenter-0   1/1     Running   0          2m

$ git diff values.yaml
diff --git a/stable/hazelcast/values.yaml b/stable/hazelcast/values.yaml
index 2be360c..779e948 100644
--- a/stable/hazelcast/values.yaml
+++ b/stable/hazelcast/values.yaml
@@ -186,7 +186,7 @@ securityContext:
 # Allows to enable a Prometheus to scrape pods, implemented for Hazelcast version >= 3.12 (or 'latest')
 metrics:
-  enabled: false
+  enabled: true
   service:
     type: ClusterIP
     port: 8080

$ klo hz-hazelcast-0
########################################
# JAVA_OPTS=-javaagent:/opt/hazelcast/lib/jmx_prometheus_javaagent.jar=8080:/opt/hazelcast/jmx_agent_config.yaml -Djava.net.preferIPv4Stack=true -Djava.util.logging.config.file=/opt/hazelcast/logging.properties -XX:MaxRAMPercentage=80.0 -XX:+UseParallelGC --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED -Dhazelcast.config=/data/hazelcast/hazelcast.yaml -DserviceName=hz-hazelcast -Dnamespace=default -Dhazelcast.shutdownhook.policy=GRACEFUL -Dhazelcast.shutdownhook.enabled=true -Dhazelcast.graceful.shutdown.max.wait=600 -Dhazelcast.jmx=true
# CLASSPATH=/opt/hazelcast/*:/opt/hazelcast/lib/*
# starting now....
########################################
+ exec java -server -javaagent:/opt/hazelcast/lib/jmx_prometheus_javaagent.jar=8080:/opt/hazelcast/jmx_agent_config.yaml -Djava.net.preferIPv4Stack=true -Djava.util.logging.config.file=/opt/hazelcast/logging.properties -XX:MaxRAMPercentage=80.0 -XX:+UseParallelGC --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED -Dhazelcast.config=/data/hazelcast/hazelcast.yaml -DserviceName=hz-hazelcast -Dnamespace=default -Dhazelcast.shutdownhook.policy=GRACEFUL -Dhazelcast.shutdownhook.enabled=true -Dhazelcast.graceful.shutdown.max.wait=600 -Dhazelcast.jmx=true com.hazelcast.core.server.HazelcastMemberStarter
Aug 06, 2020 7:28:55 AM com.hazelcast.internal.config.AbstractConfigLocator
INFO: Loading configuration '/data/hazelcast/hazelcast.yaml' from System property 'hazelcast.config'
Aug 06, 2020 7:28:56 AM com.hazelcast.internal.config.AbstractConfigLocator
INFO: Using configuration file at /data/hazelcast/hazelcast.yaml
Aug 06, 2020 7:28:56 AM com.hazelcast.instance.AddressPicker
INFO: [LOCAL] [dev] [4.0.2] Prefer IPv4 stack is true, prefer IPv6 addresses is false
Aug 06, 2020 7:28:56 AM com.hazelcast.instance.AddressPicker
INFO: [LOCAL] [dev] [4.0.2] Picked [10.36.2.3]:5701, using socket ServerSocket[addr=/0.0.0.0,localport=5701], bind any local is true
Aug 06, 2020 7:28:56 AM com.hazelcast.system
INFO: [10.36.2.3]:5701 [dev] [4.0.2] Hazelcast 4.0.2 (20200702 - 2de3027) starting at [10.36.2.3]:5701
```

Could you share your values.yaml or parameters and chart version?

**Comment by jan530** [comment] 2020-08-10 13:02
I can add to @xrow as I saw the bugs:
Helm Chart Version: hazelcast-enterprise-3.2.1
Image Version 4.0-1
everything on OpenShift 4.4

Maybe it is partly fixed in the newer Image. We saw the crash loop as the jmx_prometheus_javaagent.jar was named differently as mantioned in the startup script. The binary was named jmx_prometheus_javaagent-0.11.0.jar but in the start script it was named jmx_prometheus_javaagent.jar. Hence, the script was not finding the binary and crash looping.

Second, the configuration file was fully missing in the image: /opt/hazelcast/jmx_agent_config.yaml

Third, after manual fixing the above mentioning issues, the metrics were not accessible. We found out that the Network Policy was not modified with the metrics flag. Hence, the port 8080 for metrics was blocked. 

Does this help you?

**Comment by leszko** [comment] 2020-08-11 14:18
This is the issue fixed in Docker image version `4.0.2`. That's the bug: https://github.com/hazelcast/hazelcast-docker/issues/148

Concerning the Network Policy, I guess it's not something we can change in the Helm Chart / Operator. Right @jan530 ?

**Comment by jan530** [comment] 2020-08-12 09:15
It seems that the network policy was not created by your helm chart, it seems that one developer added this himself. Hence, this issue can be /closed :-) Thank you for your help!

**Comment by leszko** [comment] 2020-08-12 09:27
Closing. @xrow feel free to reopen if needed.

**Closed by leszko** 2020-08-12 09:27 UTC
