### ISSUE TITLE
Set default login and password for hazelcast mancenter

### ISSUE THREAD

**Issue by kudodenko** [hazelcast/charts#134] opened 2020-06-17 12:06 UTC
Provide the ability to pre-configure the username and password for hazelcast mancenter.

**Comment by mesutcelik** [comment] 2020-06-17 13:27
duplicate of https://github.com/hazelcast/charts/issues/61
will be fixed by https://github.com/hazelcast/charts/pull/77

**Closed by mesutcelik** 2020-06-17 13:27 UTC

**Comment by kudodenko** [comment] 2020-06-18 11:00
Thanks a lot!
